server:
  host: localhost
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger:
  title: Documentation de ShareEvent
  description: ShareEvent est une application de partage d'événements sur une carte interactive
  version: 1.0
  tag: user/event
  path: documentation
mongodb:
  uri: mongodb://localhost:27017/projectDB
  dbname: projectDB
mail:
  host: smtp.ethereal.email
  port: 587
  user: ismael.dicki18@ethereal.email
  pass: 5gphWRrjNcU8ZzGTyp
  
